esphome:
  name: smart-lights-x4

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ***********

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart-Lights-X4"
    password: "SmartLightsX4"

captive_portal:
    
light:
  - platform: monochromatic
    name: "Light 1"
    id: light_1
    output: l1
  - platform: monochromatic
    name: "Light 2"
    id: light_2
    output: l2
  - platform: monochromatic
    name: "Light 3"
    id: light_3
    output: l3
  - platform: monochromatic
    name: "Light 4"
    id: light_4
    output: l4


output:
  - platform: ledc
    id: l1
    pin: GPIO23
  - platform: ledc
    id: l2
    pin: GPIO25
  - platform: ledc
    id: l3
    pin: GPIO26
  - platform: ledc
    id: l4
    pin: GPIO27
    
binary_sensor:
  - platform: gpio
    name: "PB1"
    pin:
      number: GPIO32
    on_press:
      then:
        - light.toggle: light_1
  - platform: gpio
    name: "PB2"
    pin:
      number: GPIO33
    on_press:
      then:
        - light.toggle: light_2
  - platform: gpio
    name: "PB3"
    pin:
      number: GPIO34
    on_press:
      then:
        - light.toggle: light_3
  - platform: gpio
    name: "PB4"
    pin:
      number: GPIO35
    on_press:
      then:
        - light.toggle: light_4